### PR TITLE
Improve UI design

### PR DESCRIPTION
**Pull request by valentinamackovic**
With original calendar.

### CODE REVIEW

**Review by coka — CHANGES_REQUESTED** [review]
Installer code is in this PR. Can you resolve the conflicts with `master`?

**Comment by valentinamackovic** [comment]
The conflict was that new library for calendar i package.json and I removed it. So I just commit merge now?

**Comment by coka** [comment]
Hmmmm... the `react-calendar` entry in `package.json` is not on `master`. Not sure what's going on. Try to rebase instead of creating a merge commit.

**Comment by valentinamackovic** [comment]
I'm working on some unnecessary changes in index.html that I noticed a few moments ago.

**Comment by valentinamackovic** [comment]
I hope that everything is OK now.

**Review by coka — CHANGES_REQUESTED** [review]
Houston, we have a conflict. :rocket:

**Review by coka — CHANGES_REQUESTED** [review]
I would merge this, but I have a nitpick with the image. 😬 It's way too large for what we need (1717x782). We're going to replace it with a vector image of [their new logo](https://play.google.com/store/apps/details?id=com.centarsrce&hl=en_US) at some point anyway.

If we commit it to the repository, it's always going to have that "bloat" in `master`. Can you download it with a shell script? Another option is to optimize the size, or just leave the navigation bar unchanged in that part.

**Review by coka — APPROVED** [review]

**Pull request merged**
