### PR TITLE
Remodel database

### PR DESCRIPTION
**Pull request by MLazarevic36**

### CODE REVIEW

**Comment by MLazarevic36** [comment]
Change something_id to id everywhere in project, here is scheme of database
[database.pdf](https://github.com/nsoss/srce-desktop-app/files/4057656/database.pdf)

**Review by coka — CHANGES_REQUESTED** [review]
Please provide a more detailed textual description of what changes you've made.

**Comment by MLazarevic36** [comment]
In every single entity in our model, I changed column id (call_id -> id, etc.), because of dropdown implementation in form component, also, I made necessary changes to other files where id's were needed, like volunteerAction.js, AdminPanel etc. I also changed foreign key reference which was not correctly implemented, and added table ages.

**Comment by coka** [comment]
> Change something_id to id everywhere in project, here is scheme of database
> [database.pdf](https://github.com/nsoss/srce-desktop-app/files/4057656/database.pdf)

This looks good to me. :+1:

**Pull request merged**
